### ISSUE TITLE
issue with kernel packages in redhat repos

### ISSUE THREAD

**Issue by yeneryumlu** [dmc5179/nvidia-driver#2]
Thank you for your effort.

I tried to build a custom image for 4.6.9 which uses 4.18.0-193.37.1.el8_2.x86_64 kernel. I have added below line to readme.md.
     | 4.6.9-x86_64   | 4.18.0-193.37.1.el8_2.x86_64     |

But I could not complete podman/docker build. Because there is no kernel version other than kernel-headers-4.18.0-240.8.1.el8_3.x86_64 version.

The logs are below:

`
[+] Building 9.5s (7/13)
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.1s
 => => transferring dockerfile: 32B                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.1s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [internal] load metadata for registry.access.redhat.com/ubi8/ubi:8.1                                                                                                                                      0.0s
 => CACHED [1/9] FROM registry.access.redhat.com/ubi8/ubi:8.1                                                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                                             0.0s
 => => transferring context: 70B                                                                                                                                                                              0.0s
 => [2/9] COPY nvidia-driver-disconnected /usr/local/bin/nvidia-driver-disconnected                                                                                                                           0.0s
 => ERROR [3/9] RUN dnf install --setopt tsflags=nodocs -y ca-certificates curl gcc glibc.i686 make cpio kmod     elfutils-libelf elfutils-libelf-devel     "kernel-headers-4.18.0-193.37.1.el8_2.x86_64" "k  9.3s
------
 > [3/9] RUN dnf install --setopt tsflags=nodocs -y ca-certificates curl gcc glibc.i686 make cpio kmod     elfutils-libelf elfutils-libelf-devel     "kernel-headers-4.18.0-193.37.1.el8_2.x86_64" "kernel-devel-4.
18.0-193.37.1.el8_2.x86_64"     && rm -rf /var/cache/yum/*:
#7 0.973 Updating Subscription Management repositories.
#7 0.974 Unable to read consumer identity
#7 0.980 This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
#7 2.602 Red Hat Universal Base Image 8 (RPMs) - BaseOS  516 kB/s | 773 kB     00:01
#7 6.507 Red Hat Universal Base Image 8 (RPMs) - AppStre 1.3 MB/s | 4.9 MB     00:03
#7 8.816 Red Hat Universal Base Image 8 (RPMs) - CodeRea  15 kB/s |  13 kB     00:00
#7 9.192 Package ca-certificates-2019.2.32-80.0.el8_1.noarch is already installed.
#7 9.195 Package curl-7.61.1-11.el8.x86_64 is already installed.
#7 9.196 Package elfutils-libelf-0.176-5.el8.x86_64 is already installed.
#7 9.198 No match for argument: elfutils-libelf-devel
#7 9.199 No match for argument: kernel-headers-4.18.0-193.37.1.el8_2.x86_64
#7 9.201 No match for argument: kernel-devel-4.18.0-193.37.1.el8_2.x86_64
#7 9.205 Error: Unable to find a match: elfutils-libelf-devel kernel-headers-4.18.0-193.37.1.el8_2.x86_64 kernel-devel-4.18.0-193.37.1.el8_2.x86_64
------
executor failed running [/bin/sh -c dnf install --setopt tsflags=nodocs -y ca-certificates curl gcc glibc.i686 make cpio kmod     elfutils-libelf elfutils-libelf-devel     "kernel-headers-${KERNEL_VERSION}" "ker
nel-devel-${KERNEL_VERSION}"     && rm -rf /var/cache/yum/*]: exit code: 1
`

Rhcos 4.6.8 does not work either.

Result of dnf search command from ubi8 container is:

`[root@fd5c6d32e628 /]# dnf search kernel --showduplicates
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Red Hat Universal Base Image 8 (RPMs) - BaseOS                                                                                                                                     288 kB/s | 773 kB     00:02
Red Hat Universal Base Image 8 (RPMs) - AppStream                                                                                                                                  1.3 MB/s | 4.9 MB     00:03
Red Hat Universal Base Image 8 (RPMs) - CodeReady Builder                                                                                                                          7.3 kB/s |  13 kB     00:01
========================================================================================= Name & Summary Matched: kernel ==========================================================================================
kernel-headers-4.18.0-240.8.1.el8_3.x86_64 : Header files for the Linux kernel for use by glibc
============================================================================================= Summary Matched: kernel =============================================================================================
lksctp-tools-1.0.18-3.el8.i686 : User-space access to Linux Kernel SCTP
lksctp-tools-1.0.18-3.el8.x86_64 : User-space access to Linux Kernel SCTP
kmod-25-16.el8.x86_64 : Linux kernel module management utilities
libnl3-3.4.0-5.el8.x86_64 : Convenience library for kernel netlink sockets
libnl3-3.5.0-1.el8.i686 : Convenience library for kernel netlink sockets
libnl3-3.5.0-1.el8.x86_64 : Convenience library for kernel netlink sockets
systemd-udev-239-41.el8_3.1.x86_64 : Rule-based device node and kernel event manager
libkcapi-1.2.0-2.el8.i686 : User space interface to the Linux Kernel Crypto API
libkcapi-1.2.0-2.el8.x86_64 : User space interface to the Linux Kernel Crypto API
kmod-libs-25-13.el8.x86_64 : Libraries to handle kernel module loading and unloading
kmod-libs-25-16.el8.x86_64 : Libraries to handle kernel module loading and unloading
kmod-libs-25-16.el8.i686 : Libraries to handle kernel module loading and unloading
rsyslog-8.1911.0-6.el8.x86_64 : Enhanced system logging and kernel message trapping daemon
iptables-1.8.4-15.el8_3.3.x86_64 : Tools for managing Linux kernel packet filtering capabilities
iptables-1.8.4-15.el8_3.3.i686 : Tools for managing Linux kernel packet filtering capabilities

`

**Comment by dmc5179** [comment]
Sorry I did not see this message until now. There's been a known issue with the GPU operator and the kernel version for awhile now. I'll have to check if that has been resolved.

**Comment by rockocoop** [comment]
hey guys.  i just put in a pull request on this.  I managed to compile it for .29 kernel and tested on disconnected 4.6.8.  worked great

**Comment by yeneryumlu** [comment]
thanks, that worked
